url: https://biblio.ai
baseurl: ""

# Site settings
title: biblio AI  
email: justin@biblio.ai
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Justin Kelly
  pic: 1
  position: Developer
  social:
    - title: twitter
      url: https://twitter.com/_justin_kelly
    - title: github
      url: https://github.com/justinkelly/
    - title: linkedin
      url: #

- name: State Library of Victoria
  pic: slv-logo.png
  position: Support and Funding
  social:
    - title: twitter
      url: https://twitter.com/Library_Vic
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Swinburne University
  pic: swin-logo.jpg
  position: Development Partner
  social:
    - title: twitter
      url: https://twitter.com/swinlib
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/_justin_kelly
  - title: facebook
    url:
  - title: github
    url: https://github.com/justinkelly/biblio.ai

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
